// Private public-observation replay only; no input, hidden code, save access, or output files.
const fs=require('fs'),r=JSON.parse(fs.readFileSync('artifacts/slot1-playthrough/5-5.json','utf8').replace(/^\uFEFF/,''));
const si=r.events.findLastIndex(e=>e.observation?.frame===3389608);if(si<0)throw Error('Actual4 source absent');const o=r.events[si].observation,t=o.level.timelines[0],V=[[0,1],[-1,0],[0,-1],[1,0]],K=z=>z.join(','),M=(z,d)=>[z[0]+V[d][0],z[1]+V[d][1]];
const wall=new Set(t.entities.filter(e=>e.type==='SOLID'&&e.blockable).map(e=>K(e.pos))),floor=new Set([...t.tiles,...t.entities.filter(e=>e.floor)].map(e=>K(e.pos))),goals=new Set(o.level.goals.map(K)),base=new Map(t.entities.filter(e=>e.type!=='SOLID').map(e=>[e.id,e]));
if(t.tiles.some(e=>e.type!=='SOLID'))throw Error('Unexpected special terrain');
const from=tt=>({time:tt.time,p:tt.entities.filter(e=>e.type==='PLAYER'&&e.active).map(e=>({id:e.id,z:e.pos.slice(),f:e.properties.face,F:e.properties.split})),b:tt.entities.filter(e=>e.type==='BOX').map(e=>({id:e.id,z:e.pos.slice(),active:e.active,shadow:e.details.Shadow})),forkActive:tt.entities.find(e=>e.id===53).active});
const source=from(t);if(o.level.instructions!=='SAAA'||source.p.length!==1||source.b.find(b=>b.id===56).active)throw Error('Actual4 Shadow collapse differs');
function step(s,a,observeShadow=true){const d0='WASD'.indexOf(a),bm=new Map(s.b.filter(b=>b.active).map(b=>[K(b.z),b.id])),plans=new Map(),np=[],upper=s.b.some(b=>b.active&&K(b.z)==='1,4')||s.p.some(p=>K(p.z)==='1,4');
 const block=z=>wall.has(K(z))||!floor.has(K(z))||K(z)==='1,6'&&!upper;
 function chain(z,d){const ch=[];while(bm.has(K(z))){ch.push(bm.get(K(z)));z=M(z,d);}return block(z)?null:ch;}
 for(const p of s.p){let z=p.z.slice(),f=d0;for(let j=0;j<4;j++){const d=(d0+j)%4,n=M(p.z,d);if(block(n))continue;const ch=chain(n,d);if(ch===null)continue;for(const id of ch){if(plans.has(id)&&plans.get(id)!==d)throw Error('Force unknown');plans.set(id,d);}z=n;f=d;break;}np.push({...p,z,f});}
 let forkActive=s.forkActive;for(const p of np)if(forkActive&&K(p.z)==='1,7'){p.F++;forkActive=false;}
 const nb=s.b.map(b=>({...b,z:plans.has(b.id)?M(b.z,plans.get(b.id)):b.z.slice()}));
 if(new Set(nb.filter(b=>b.active).map(b=>K(b.z))).size!==nb.filter(b=>b.active).length)throw Error('Stack unknown');if(new Set(np.map(p=>K(p.z))).size!==np.length)throw Error('Player contact unknown');
 if(np.some(p=>nb.some(b=>b.active&&K(p.z)===K(b.z))))throw Error('Shadow cargo unknown');
 for(const b of nb)if(observeShadow&&plans.has(b.id)&&b.shadow&&goals.has(K(b.z)))b.active=false;
 return {time:s.time+1,p:np,b:nb,forkActive};
}
function desc(s){const upper=s.b.some(b=>b.active&&K(b.z)==='1,4')||s.p.some(p=>K(p.z)==='1,4');return {time:s.time,players:s.p.map(p=>({id:p.id,pos:p.z,face:p.f,Fork:p.F})),boxes:s.b,gateBlockable:!upper,forkActive:s.forkActive,entityPredictions:[...base.values()].filter(e=>e.type!=='PLAYER'||s.p.some(p=>p.id===e.id)).map(e=>{const p=s.p.find(p=>p.id===e.id),b=s.b.find(b=>b.id===e.id);if(p)return {...e,pos:p.z,face:V[p.f],properties:{...e.properties,face:p.f,split:p.F}};if(b)return {...e,pos:b.z,active:b.active};if(e.id===53)return {...e,active:s.forkActive};if(e.id===58)return {...e,blockable:!upper};return e;})};}
function diff(expected,tt){const d=[];for(const ex of expected){const ac=tt.entities.find(e=>e.id===ex.id);if(!ac){d.push({id:ex.id,key:'missing'});continue;}for(const k of new Set([...Object.keys(ex),...Object.keys(ac)]))if(JSON.stringify(ex[k])!==JSON.stringify(ac[k]))d.push({id:ex.id,key:k,expected:ex[k],actual:ac[k]});}return d;}
const i0=r.events.findIndex(e=>e.observation?.frame===3361851),i3=r.events.findLastIndex(e=>e.observation?.level.instructions==='SAA');let priorCalibration=null;
if(i0>=0){const tt=r.events[i0].observation.level.timelines[0];let s=from(tt);for(const a of 'SAA')s=step(s,a,false);const beforeA4=desc(s),checks=[];if(i3>=0)checks.push({event:i3,frame:r.events[i3].observation.frame,fullEntityDiff:diff(beforeA4.entityPredictions,r.events[i3].observation.level.timelines[0])});s=step(s,'A');checks.push({event:si,frame:o.frame,fullEntityDiff:diff(desc(s).entityPredictions,t)});priorCalibration={beforeA4,actualShadow56Rule:{pos:[3,1],active:false,Shadow:true,maskedoff:0},checks,scope:'Actual56 deactivation onGoal observed; does not prove allShadow/containment cases.'};}
let s=source;const path='AWWSSDDDWWWAAAAWAWWSSSSSWWDDSW',trace=[];for(const a of path){s=step(s,a);trace.push({action:a,...desc(s)});}if(K(s.p[0].z)!=='3,4'||s.p[0].f!==0||s.p[0].F!==1||s.b.some(b=>b.active))throw Error('Owner ordinary30 geometry differs');
const candidate={prefix30:path,trace,preA19:trace[13],singleA19:trace[14],preS28:trace[22],singleS28:trace[23],preX34:desc(s),birth35Geometry:{time:35,original57:{pos:[2,4],face:0,Fork:0},newUnknownID:{pos:[4,4],face:0,Fork:0},scope:'Empty safe ordinary birth; actual newID/GMID required'},tail4:'ASSS',tailGoal39:[[1,1],[3,1]],scope:'Owner hand39; A19 Shadow pressure/S28 secondShadow Goal/X35 independent checks; no search.'};
const walls=t.entities.filter(e=>e.type==='SOLID'),prefixChecks=[];for(let i=si+1;i<r.events.length;i++){const oo=r.events[i].observation;if(!oo)continue;const n=oo.level.instructions.length-o.level.instructions.length;if(n<1||n>30||oo.level.instructions!==o.level.instructions+path.slice(0,n))continue;prefixChecks.push({event:i,frame:oo.frame,time:oo.level.timelines[0].time,fullEntityDiff:diff(trace[n-1].entityPredictions.concat(walls),oo.level.timelines[0]),tilesEqual:JSON.stringify(oo.level.timelines[0].tiles)===JSON.stringify(t.tiles)});}
let actualBirth35=null,tailAudit=null,completionEvidence=null;const i35=r.events.findLastIndex(e=>e.observation?.frame===3450894);
if(i35>=0){const bo=r.events[i35].observation,bt=bo.level.timelines[0],child=bt.entities.find(e=>e.type==='PLAYER'&&e.id!==57),pred=desc(s).entityPredictions.map(e=>e.id===57?{...e,pos:[2,4],properties:{...e.properties,split:0}}:e);pred.push({...base.get(57),id:child.id,pos:[4,4],face:V[0],properties:{...base.get(57).properties,face:0,split:0},details:{...base.get(57).details,GMID:child.details.GMID}});
 actualBirth35={event:i35,frame:bo.frame,actualAllocation:{newID:child.id,newGMID:child.details.GMID,timelineID:bt.id},fullEntityDiff:diff(pred.concat(walls),bt),tilesEqual:JSON.stringify(bt.tiles)===JSON.stringify(t.tiles),scope:'Empty safe birth geometry validated; allocation read fromactual35, not predicted'};
 base.set(child.id,child);let ts=from(bt);const tailTrace=[];for(const a of 'ASSS'){ts=step(ts,a);tailTrace.push({action:a,...desc(ts)});}const checks=[];for(let i=i35+1;i<r.events.length;i++){const oo=r.events[i].observation;if(!oo)continue;const n=oo.level.instructions.length-bo.level.instructions.length;if(n<1||n>4||oo.level.instructions!==bo.level.instructions+'ASSS'.slice(0,n))continue;const dd=diff(tailTrace[n-1].entityPredictions.concat(walls),oo.level.timelines[0]);checks.push({event:i,frame:oo.frame,time:oo.level.timelines[0].time,fullEntityDiff:dd,physicsStaticDiff:dd.filter(v=>v.key!=='anim_completed'),tilesEqual:JSON.stringify(oo.level.timelines[0].tiles)===JSON.stringify(t.tiles)});}tailAudit={path:'ASSS',trace:tailTrace,checks};
 if(r.completion){const co=r.completion,dd=diff(tailTrace.at(-1).entityPredictions.concat(walls),co.level.timelines[0]);completionEvidence={frame:co.frame,completed:co.level.completed,actionCount:r.run?.action_count,exactCandidate:co.level.instructions==='SAAA'+path+'XASSS',fullEntityDiff:dd,physicsStaticDiff:dd.filter(v=>v.key!=='anim_completed'),tilesEqual:JSON.stringify(co.level.timelines[0].tiles)===JSON.stringify(t.tiles),undoCount:r.run?.undo_count,retryCount:r.run?.retry_count,scope:'Full actual39 completed frame kept; final PLAYER animation false preserved, no fabricated stable frame.'};}}
module.exports={source,step,desc,diff,r,t,candidate};
if(require.main===module)console.log(JSON.stringify({sourceEvent:si,sourceFrame:o.frame,priorCalibration,candidate,prefixChecks,actualBirth35,tailAudit,completionEvidence,expanded:0,handle:null,scope:'No game input. Shadow56/55 Goal deactivation actual; owner hand39 complete with final animation limitation. No search.'}));
